# Generated by Django 4.2.3 on 2023-07-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
